---
- name: install ngnix and copy index file to ansible server
  hosts: servers
  become: yes
  tasks:
    - name: install nginx
      apt:
       name: nginx
       state: latest
       update_cache: yes
    - name: start nginx
      service:
       name: nginx
       state: started
    - name: copy index file to sever
      copy:
       src: /home/sachin/files/ansiterra-test/index.html
       dest: /var/www/html/index.html
